-- Tabela Paciente
CREATE SEQUENCE SEQ_ID_PACIENTE increment by 1 minvalue 0;

ALTER TABLE PACIENTE DROP COLUMN SINTOMA;
ALTER TABLE PACIENTE ADD CHAVE VARCHAR2(255);
ALTER TABLE PACIENTE MODIFY ALTURA NUMBER(9,7);
ALTER TABLE PACIENTE MODIFY PESO NUMBER(9,7);
select SEQ_ID_PACIENTE.currval FROM DUAL;

ALTER TABLE PACIENTE ADD CONSTRAINT PK_ID_PACIENTE PRIMARY KEY (ID);

INSERT INTO PACIENTE VALUES (SEQ_ID_PACIENTE.NEXTVAL,'Horacio Conrrado',to_date('03/03/2013','dd/mm/yyyy'),'43242342243','323123211',to_date('03/03/1993','dd/mm/yyyy'),1.85,101.800,'O+','Datilotamina','5511933442255','Americo de Alencar',1,'13B','HC013452');

-- Tabela medicamentos
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT PK_ID_MEDICAMENTO PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_ID_MEDICAMENTO increment by 1 minvalue 0;
INSERT INTO MEDICAMENTOS VALUES (SEQ_ID_MEDICAMENTO.NEXTVAL,'Cloridrato de Potassio','Sazonian','2mg de cloro, 3 de potÃ¡ssio','13','Auricular','NÃ£o usar em casos de gripe forte');

-- Tabela diagnosticos
ALTER TABLE DIAGNOTICOS RENAME TO DIAGNOSTICOS;
INSERT INTO DIAGNOSTICOS VALUES (9,'Dores nas costas');
INSERT INTO DIAGNOSTICOS VALUES (9,'DepressÃ£o');
ALTER TABLE DIAGNOSTICOS ADD CONSTRAINT FK_DIAG_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID);

-- Tabela Consideracoes Medicas
ALTER TABLE CONSIDERACOES_MEDICAS ADD CONSTRAINT FK_CONSID_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID);

-- Tabela Paciente Medicamentos
ALTER TABLE PACIENTE_MEDICAMENTO ADD CONSTRAINT FK_PAC_MED_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID);
ALTER TABLE PACIENTE_MEDICAMENTO ADD CONSTRAINT FK_PAC_MED_ID_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTOS(ID);
INSERT INTO PACIENTE_MEDICAMENTO VALUES (9,1);
ALTER TABLE MEDICAMENTOS MODIFY MODO_USO VARCHAR2(255);

-- Tabela Sintomas
ALTER TABLE SINTOMAS ADD CONSTRAINT PK_ID_SINTOMA PRIMARY KEY (ID_SINTOMA);
CREATE SEQUENCE SEQ_ID_SINTOMA increment by 1 minvalue 0;
INSERT INTO SINTOMAS VALUES (SEQ_ID_SINTOMA.NEXTVAL,'Tristeza continua');
INSERT INTO SINTOMAS VALUES (SEQ_ID_SINTOMA.NEXTVAL,'Dores corporais');
INSERT INTO SINTOMAS VALUES (SEQ_ID_SINTOMA.NEXTVAL,'Tosse continua');

-- Tabela Sintoma Paciente
ALTER TABLE SINTOMA_PACIENTE ADD CONSTRAINT FK_SINT_PAC_ID_SINTOMA FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID);
ALTER TABLE SINTOMA_PACIENTE ADD CONSTRAINT FK_SINT_PAC_ID_PACIENTE FOREIGN KEY (ID_SINTOMA) REFERENCES SINTOMAS(ID_SINTOMA);
INSERT INTO SINTOMA_PACIENTE VALUES (9,1);
INSERT INTO SINTOMA_PACIENTE VALUES (9,2);

-- AlteraÃ§Ãµes Futuras:
--ALTER TABLE CONSIDERACOES_MEDICAS ADD CONSTRAINT FK_CONSID_ID_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID);
--ALTER TABLE PACIENTE ADD CONSTRAINT FK_ID_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID);
